### ISSUE TITLE
Crash when placing any sign from Natures Spirit

### ISSUE THREAD

**Issue by sleepy-evelyn** [Team-Hibiscus/NatureSpirit#16]
Happening with the latest version of Natures Spirit (1.1). I do also have the latest version of Sodium + Indium installed

**Log:** https://gist.github.com/sleepy-evelyn/bc142fc9c7f754da6e1d8b9735d34d2c

**Comment by sleepy-evelyn** [comment]
I'm also getting this in the log which could be useful.

```
[19:33:12] [Render thread/WARN]: Failed to generate hanging sign extension texture for natures_spirit:redwood. Could be that the target mod isnt registering their wood type properly
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_4730.method_24147()" because the return value of "net.minecraft.class_4722.method_45781(net.minecraft.class_4719)" is null
	at net.mehvahdjukaar.supplementaries.dynamicpack.ClientDynamicResourcesGenerator.regenerateDynamicAssets(ClientDynamicResourcesGenerator.java:238) ~[transformed-mod-supplementaries.i0:0/:?]
	at net.mehvahdjukaar.moonlight.api.resources.pack.DynResourceGenerator.reloadResources(DynResourceGenerator.java:115) ~[transformed-mod-moonlight.i0:0/:?]
	at net.mehvahdjukaar.moonlight.api.resources.pack.DynResourceGenerator.onEarlyReload(DynResourceGenerator.java:84) ~[transformed-mod-moonlight.i0:0/:?]
	at net.mehvahdjukaar.moonlight.api.events.fabric.MoonlightEventsHelperImpl.lambda$postEvent$1(MoonlightEventsHelperImpl.java:27) ~[transformed-mod-moonlight.i0:0/:?]
	at java.util.concurrent.ConcurrentLinkedDeque.forEach(ConcurrentLinkedDeque.java:1650) ~[?:?]
	at net.mehvahdjukaar.moonlight.api.events.fabric.MoonlightEventsHelperImpl.postEvent(MoonlightEventsHelperImpl.java:27) ~[transformed-mod-moonlight.i0:0/:?]
	at net.mehvahdjukaar.moonlight.api.events.MoonlightEventsHelper.postEvent(MoonlightEventsHelper.java) ~[transformed-mod-moonlight.i0:0/:?]
	at net.minecraft.class_6861.handler$znb000$moonlight$dynamicPackEarlyReload(class_6861.java:534) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_6861.<init>(class_6861.java:60) ~[transformed-mod-minecraft.i0:0/:?]
	at org.quiltmc.qsl.resource.loader.impl.ResourcePackRegistrationContextImpl.<init>(ResourcePackRegistrationContextImpl.java:43) ~[transformed-mod-quilt-resource-loader.i0:0/:?]
	at org.quiltmc.qsl.resource.loader.impl.ResourceLoaderImpl.buildMinecraftResourcePack(ResourceLoaderImpl.java:406) ~[transformed-mod-quilt-resource-loader.i0:0/:?]
	at net.minecraft.class_1065.handler$jjd001$quilt_resource_loader$onPackGet(class_1065.java:576) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_1065.method_45855(class_1065.java:88) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_3288.method_45274(class_3288.java:70) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_3288.method_45275(class_3288.java:47) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_1065.method_45257(class_1065.java:88) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_7678.method_14453(class_7678.java:39) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_3283.method_29212(class_3283.java:39) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_3283.method_14445(class_3283.java:32) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_310.<init>(class_310.java:513) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.client.main.Main.main(Main.java:211) ~[1.20.1-0.21.0-beta.4.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:524) ~[quilt-loader-0.21.0-beta.4.jar:?]
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:84) ~[quilt-loader-0.21.0-beta.4.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28) ~[quilt-loader-0.21.0-beta.4.jar:?]
	```

**Comment by sleepy-evelyn** [comment]
This seems like a double issue tbh. I removed supplementaries thinking that might be the issue and got this instead.

https://gist.github.com/sleepy-evelyn/4e83b85240cd5a21b22355b5c0a91d98

**Comment by Eko-byte** [comment]
you may have another mod causing something like this to happen

**Comment by sleepy-evelyn** [comment]
This is a conflict with TerraformerMCs wood API from Terraform. Specifically this mixin: https://github.com/TerraformersMC/Terraform/blob/7783a401d60b2b1bb8398207bb97018a5f3e86b6/terraform-wood-api-v1/src/main/java/com/terraformersmc/terraform/sign/mixin/MixinSignBlockEntityRenderer.java#L33

Idk which mod needs to change. I included a more detailed issue now I know where the issue lies on the terraform issue page. It might need resolving here idk.

**Terraform issue**: https://github.com/TerraformersMC/Terraform/issues/81

**Comment by sleepy-evelyn** [comment]
Nevermind that isn't the issue. The log without Sodium & Terraform wood API: https://bytebin.lucko.me/9ZNlc01m7M

**Comment by haykam821** [comment]
[This debug mod](https://github.com/Team-Hibiscus/NatureSpirit/files/13161108/unregisteredwoodtypewarning-0.0.0.jar.zip) should prevent the game from crashing and log information about unregistered wood types to help track down the issue.

**Comment by sleepy-evelyn** [comment]
> [This debug mod](https://github.com/Team-Hibiscus/NatureSpirit/files/13161108/unregisteredwoodtypewarning-0.0.0.jar.zip) should prevent the game from crashing and log information about unregistered wood types to help track down the issue.

It stops the crash instead placing an oak sign but I can't see anything in the log. I'm not sure how to turn on log4j debug comments in the modrinth launcher tbh

**Comment by Eko-byte** [comment]
very odd ill have to look into this
