### ISSUE TITLE
Caused by: java.lang.IllegalStateException: Feature order cycle found, involved sources: [Reference{ResourceKey[minecraft:worldgen/biome / natures_spirit:carnation_fields]=net.minecraft.world.biome.Biome@7cc036f8}, Reference{ResourceKey[minecraft:worldgen/biome / newworld:wooded_meadow]=net.minecraft.world.biome.Biome@ef2f74}] 	at net.minecraft.world.gen.feature.util.PlacedFeatureIndexer.collectIndexedFeatures(PlacedFeatureIndexer.java:100) ~[client-intermediary.jar:?] 	at net.minecraft.world.gen.chunk.ChunkGenerator.method_44215(ChunkGenerator.java:102) ~[client-intermediary.jar:?]

### ISSUE THREAD

**Issue by inikishev** [Team-Hibiscus/NatureSpirit#19]
its incompatible with https://modrinth.com/mod/new_world
https://gist.github.com/stunlocked1/34bf4792f8bed6f04ccaaa7199e446f0 is the log

```
Caused by: java.lang.IllegalStateException: Feature order cycle found, involved sources: [Reference{ResourceKey[minecraft:worldgen/biome / natures_spirit:carnation_fields]=net.minecraft.world.biome.Biome@7cc036f8}, Reference{ResourceKey[minecraft:worldgen/biome / newworld:wooded_meadow]=net.minecraft.world.biome.Biome@ef2f74}]
```

**Comment by Eko-byte** [comment]
Please look at the built in datapacks and use newworld compatibility
