### ISSUE TITLE
Crash Loading 1.20.1’s latest patch

### ISSUE THREAD

**Issue by PeglinX** [Team-Hibiscus/NatureSpirit#48]
This crash occurs while loading in 1.20.1 latest patch. It is not a mod incompatibility

https://mclo.gs/sRNZlzx

**Comment by FireNneon** [comment]
I also crash on start up, it's when I use the latest Version of NatureSpirit, the error I get is as followed.

Uncaught exception in thread "main"
java.lang.RuntimeException: Error creating Mixin config naturespirit.mixins.json for mod natures_spirit
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:96)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:151)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: org.spongepowered.asm.launch.MixinInitialisationError: Error initialising mixin config naturespirit.mixins.json
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:153)
	at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:100)
	at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:87)
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:94)
	... 3 more
Caused by: java.lang.IllegalArgumentException: The requested compatibility level JAVA_21 could not be set. Level is not supported by the active JRE or ASM version (Java 17.0, ASM 9.6 (ASM10_EXPERIMENTAL))
	at org.spongepowered.asm.mixin.MixinEnvironment.setCompatibilityLevel(MixinEnvironment.java:1627)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.initCompatibilityLevel(MixinConfig.java:557)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInit(MixinConfig.java:502)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.onLoad(MixinConfig.java:430)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:1293)
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:148)
	... 6 more

**Comment by PeglinX** [comment]
yeah same error. Do you have a rudimentary fix btw?

**Comment by FireNneon** [comment]
sorry for the late response, I just downgraded by a version, it works fine on the pervious release, just the latest 1.20.1 release crashes on startup, the crash was tested with the latest 1.20.1 NaturesSpirit release, and no other mods, so it's a bug with the latest release of NaturesSpirit for 1.20.1

**Comment by PeglinX** [comment]
thanks, no worries. I’ll update the post with your info

**Comment by PeglinX** [comment]
This has been fixed as of the most recent patch
