### ISSUE TITLE
Nature's Spirit doesn't work on 1.21.1

### ISSUE THREAD

**Issue by ghost** [Team-Hibiscus/NatureSpirit#81]
Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'Nature's Spirit' (natures_spirit) 1.6.2-1.21 with any version that is compatible with:
		 - minecraft 1.21.1
More details:
	 - Mod 'Nature's Spirit' (natures_spirit) 1.6.2-1.21 requires version 1.21 of 'Minecraft' (minecraft), but only the wrong version is present: 1.21.1!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:196)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by uczpre** [comment]
it does support it , it just doesnt work. change the title lol

**Comment by ghost** [comment]
You're right, I changed the title.
