### ISSUE TITLE
Unable to shoot bows in survival when cheese arrows are disabled

### ISSUE THREAD

**Issue by alittlewarlord** [Team-Hibiscus/NatureSpirit#87]
**Mod version:** 1.6.3-1.20.1 (also encountered in 1.6.2-1.20.1) for Fabric

The title says it all, really. Turning off cheese arrows seems to disable bow use *entirely*, no matter what arrows you do or do not have in your inventory in Survival. It doesn't seem to output anything in the game log either, and doesn't crash or anything. It just... doesn't let me nock any arrows. 
Reenabling cheese arrows fixes it, and I haven't noticed any other archery-related issues tied to that setting. I'm just a bit baffled that this is happening, and thought you should know. 😅

**Comment by FoketzoRAI** [comment]
@alittlewarlord Man, I have the same issue. It's very strange. I guess devs should think about the fix as it's very annoying.

+ It doesn't matter whether `cheese_arrow` is enabled or not. It just doesn't work.

**Comment by FoketzoRAI** [comment]
@Eko-byte Please, could you check this bug with `cheese_arrow` misc feature?

Version of Nature spirit is 1.6.3-1.20.1

It makes the use of bow and crossbow impossible.

<details>

<summary>Log</summary>

```log
[23:09:29] [Render thread/ERROR]: Parsing error loading recipe natures_spirit:cheese_arrow
com.google.gson.JsonSyntaxException: Unknown item 'natures_spirit:cheese_arrow'

	at net.minecraft.class_1869.method_17878(class_1869.java:272) ~[client-intermediary.jar:?]
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at net.minecraft.class_1869.method_8155(class_1869.java:272) ~[client-intermediary.jar:?]
	at net.minecraft.class_1869.method_35228(class_1869.java:259) ~[client-intermediary.jar:?]
	at net.minecraft.class_1869$class_1870.method_8164(class_1869.java:293) ~[client-intermediary.jar:?]
	at net.minecraft.class_1869$class_1870.method_8121(class_1869.java:279) ~[client-intermediary.jar:?]
	at net.minecraft.class_1863.method_17720(class_1863.java:135) ~[client-intermediary.jar:?]
	at net.minecraft.class_1863.method_20705(class_1863.java:56) ~[client-intermediary.jar:?]
	at net.minecraft.class_1863.method_18788(class_1863.java:35) ~[client-intermediary.jar:?]
	at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:762) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:526) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:69) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:139) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_18857(class_310.java:16017) ~[client-intermediary.jar:?]
	at net.minecraft.class_525.method_31130(class_525.java:352) ~[client-intermediary.jar:?]
	at net.minecraft.class_526.method_19944(class_526.java:60) ~[client-intermediary.jar:?]
	at net.minecraft.class_4185.method_25306(class_4185.java:94) ~[client-intermediary.jar:?]
	at net.minecraft.class_4264.method_25348(class_4264.java:56) ~[client-intermediary.jar:?]
	at net.minecraft.class_339.method_25402(class_339.java:189) ~[client-intermediary.jar:?]
	at net.minecraft.class_4069.method_25402(class_4069.java:38) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1611(class_312.java:98) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25412(class_437.java:409) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1601(class_312.java:98) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22686(class_312.java:169) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:102) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22684(class_312.java:169) ~[client-intermediary.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) ~[lwjgl-glfw-3.3.1.jar:?]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar:?]
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474) ~[lwjgl-glfw-3.3.1.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:237) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1244) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[Fabric%201.20.1.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.16.9.jar:?]
...
[23:09:28] [Worker-ResourceReload-15/ERROR]: Couldn't load tag minecraft:arrows as it is missing following references: natures_spirit:cheese_arrow (from fabric)
```

</details>

**Comment by FoketzoRAI** [comment]
https://github.com/user-attachments/assets/edd0dc15-cbe8-49e0-a04b-7d6cafec410a

**Comment by Eko-byte** [comment]
I've been working on fixing this issue, for the next release for 1.20.1, and for the next release for 1.21.1, it will be fixed i hope, I havent had the time to work on the mod as I wish I could

**Comment by Eko-byte** [comment]
can you give me a list of mods you are using? this bug only seems to happen on some weird load cycle and with specific mods it seems

**Comment by FoketzoRAI** [comment]
@Eko-byte Sure:

[mods.txt](https://github.com/user-attachments/files/17879565/mods.txt)

**Comment by Eko-byte** [comment]
for now I'd not use Nature's Delight, I need to rework the code it seems for that mod, but essentially whats happening is that farmer's delight refabricated uses a library which gives different functionality for porting mods from forge, and nature's delight references things from farmer's delight and nature's spirit at once causing loading issues i think? that is my theory
