### ISSUE TITLE
Incompatibility / conflict with Regenerations

### ISSUE THREAD

**Issue by Rebel459** [Team-Hibiscus/NatureSpirit#9]
https://modrinth.com/mod/regenerations

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'natures_spirit'!
 
    at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
    at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
    at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
    at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
    at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
    at net.minecraft.class_310.<init>(class_310.java:458)
    at net.minecraft.client.main.Main.main(Main.java:211)

---(shortened for clarity and cus idk discord formatting)---
 
Caused by: java.lang.RuntimeException: Attempted to register ID ResourceKey[minecraft:worldgen/trunk_placer_type / minecraft:maple_trunk_placer] at different raw IDs (10, 18)! If you're trying to override an item, use .set(), not .register()!
    at net.minecraft.class_2370.handler$cka000$fabric-registry-sync-v0$setPre(class_2370.java:705)
    at net.minecraft.class_2370.method_46744(class_2370.java)
    at net.minecraft.class_2370.method_10272(class_2370.java:186)
    at net.minecraft.class_2378.method_39197(class_2378.java:118)
    at net.minecraft.class_2378.method_10230(class_2378.java:114)
    at net.minecraft.class_2378.method_10226(class_2378.java:110)
    at net.minecraft.class_5142.method_26995(class_5142.java:19)
    at net.minecraft.class_5142.callRegister$naturesspirit$md$f617b2$0(class_5142.java)
    at net.hibiscus.naturespirit.mixin.TrunkPlacerTypeMixin.callRegister(TrunkPlacerTypeMixin.java)
    at net.hibiscus.naturespirit.util.HibiscusWorldGen.<clinit>(HibiscusWorldGen.java:40)

**Comment by Rebel459** [comment]
resolved in a beta release, so this issue is pointless

**Comment by Rebel459** [comment]
1.1 has released, which fixes this issue
